**FTDS NG-6**

Instruksi

1. Apakah [1 3] adalah eigenvector dari [[1 -1] [6 4]]? Jika iya, berapakah eigenvalue nya?

In [11]:
from numpy import array
from numpy.linalg import eig

A = array([[1, -1], [6, 4]])
values, vectors = eig(A)

print(vectors)
print(values)

[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]
[2.5+1.93649167j 2.5-1.93649167j]


Dari hasil eigenvector di atas, tidak ada [1 3], sehingga [1, 3] bukanlah eigenvector dari matriks A

In [7]:
B = array([1, 3])

In [13]:
B

array([1, 3])

In [14]:
A

array([[ 1, -1],
       [ 6,  4]])

In [8]:
A.dot(B)

array([-2, 18])

Hasil di atas adalah perkalian dot (dot product) dari A dan B. Dapat dilihat jelas bahwa hasil dot product dari A dan B bukan merupakan bagian (hasil perkalian) dari [1, 6] maupun [-1, 4].