**FTDS NG-5**

Instruksi

1. Buatlah Tensor sesuai perintah
2. Lakukan perkalian terhadap matriks sesuai perintah
3. Lakukan:\
   a. Transponse\
   b. Hitung determinan\
   c. Inverse\
   terhadap matriks sesuai perintah

In [2]:
#Nomor 1

import numpy as np

tensor_1 = np.array([
                [[[23, 50], [7, 12]], [[57, 67], [99, 43]]],
                [[[75, 21], [57, 12]], [[87, 26], [18, 84]]]
            ])
print(tensor_1.shape)
print(tensor_1)

(2, 2, 2, 2)
[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


In [4]:
#Nomor 2

matrix_a = np.array([
                [23, 50, 19],
                [7, 12, 109],
                [57, 67, 98]
            ])
matrix_b = np.array([[17], [22], [19]])

multiply_matrix = matrix_a * matrix_b

print(matrix_a)
print(matrix_b)
print("******")
print(multiply_matrix)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]
******
[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


In [6]:
#Nomor 3 bagian A

matrix_a_transpose = matrix_a.transpose()

print(matrix_a)
print(matrix_a_transpose)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [7]:
#Nomor 3 bagian B

matrix_a_determinant = np.linalg.det(matrix_a)

print(matrix_a)
print(matrix_a_determinant)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
131344.0000000002


In [8]:
#Nomor 3 bagian C

matrix_a_inverse = np.linalg.inv(matrix_a)

print(matrix_a)
print(matrix_a_inverse)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
